Account System
silon-j/archi_app_store_server pull request #1
Opened 2024-08-27 11:53 UTC by Guanda0120

## 基础用户API完成
- 用户登录
- 更换密码
- 获取验证码
- 用户注册

## parser 修改
- Argument _check_type 功能修改，原来是不是有点问题

## TODOs
- 增加unittest
- 更多错误测试

2024-08-28 01:43 UTC, silon-j commented on apps/account/Views/change_password_view.py
> +    # ERROR MSG
错误信息应该在error中统一定义统一管理

2024-08-28 01:44 UTC, silon-j commented on apps/account/Views/change_password_view.py
> +        if form is None:
你已经parser里面有required了，不会出现form 为none的情况，解析器帮你做好处理了

2024-08-28 01:46 UTC, silon-j commented on apps/account/Views/change_password_view.py
> +        account = Account.objects.filter(username=form.username).first()
你如果加了中间件，这里也不用重新搜一遍用户，已经携带在request里面了

2024-08-28 01:55 UTC, silon-j commented on apps/account/models.py
> +class EmailAuthCodeForWhat(Enum):
choice 写法不规范，https://docs.djangoproject.com/zh-hans/4.2/ref/models/fields/

2024-08-28 01:55 UTC, silon-j commented on apps/account/Views/change_password_view.py
> +        vertify_code = AccountEmailAuthCode.objects.filter(email=account.email, for_what = EmailAuthCodeForWhat.PASSWORD.value, is_valid = True).first()
这里建议order by -id ,保证尝试用最新的进行匹配

2024-08-28 01:58 UTC, silon-j commented on apps/account/Views/change_password_view.py
> +        if vertify_code is None:
没有认证成功一律反400就行，这里的判断可以优化，例如
if vertify_code and vertify.code == form.code

2024-08-28 02:01 UTC, silon-j commented on apps/account/Views/change_password_view.py
> +        vertify_code = AccountEmailAuthCode.objects.filter(email=account.email, for_what = EmailAuthCodeForWhat.PASSWORD.value, is_valid = True).first()
为什么不检查过期时间

2024-08-28 02:03 UTC, silon-j commented on apps/account/Views/login_view.py
> +    @swagger_auto_schema(
API管理应该在yapi里面做

2024-08-28 02:05 UTC, silon-j commented on apps/account/Views/login_view.py
> +            ip=request.META.get('REMOTE_ADDR', ''),
ip在utils有工具函数

2024-08-28 02:06 UTC, silon-j commented on apps/account/Views/login_view.py
> +        if account == None:
none不应该用==判断，而且这里建议用exists方法判断

2024-08-28 02:14 UTC, silon-j commented on manage.py
> +    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'server.settings.local')
启动方式不应该修改，调试需要自行设置启动命令--setting=settings.local

2024-08-28 02:15 UTC, silon-j commented on server/settings.py
> +For the full list of settings and their values, see
该文件不需要

2024-08-28 02:23 UTC, Guanda0120 commented on apps/account/Views/change_password_view.py
> +        vertify_code = AccountEmailAuthCode.objects.filter(email=account.email, for_what = EmailAuthCodeForWhat.PASSWORD.value, is_valid = True).first()
这个没在filter当中查找，我修改以下，我们查表需要使用 with transcation.atomic:

2024-08-28 02:23 UTC, Guanda0120 commented on apps/account/Views/login_view.py
> +    @swagger_auto_schema(
OK

2024-08-28 02:30 UTC, silon-j commented on .env
> +DATABASE_POSTGRES_NAME=appstore
这文件一般不传明文上来

2024-08-28 02:32 UTC, silon-j commented on apps/account/apps.py
> +class AccountConfig(AppConfig):
这文件应该没啥用

2024-08-28 02:33 UTC, silon-j commented on apps/account/migrations/0001_initial.py
> +    dependencies = [
后续开发建议一次性迁移，避免数据丢失

2024-08-28 02:33 UTC, Guanda0120 commented on apps/account/migrations/0001_initial.py
> +    dependencies = [
OK

2024-08-28 02:34 UTC, silon-j commented on apps/account/models.py
> +    for_what = models.SmallIntegerField(choices=[(tag.value, tag.name) for tag in EmailAuthCodeForWhat])
命名建议使用type等方式表达

2024-08-28 02:36 UTC, silon-j commented on libs/email/netease.py
> +
没改动的就不要提交了

2024-08-28 02:36 UTC, silon-j commented on libs/boost/middleware.py
>          logger.info(f"Request processed in {duration:.2f} seconds. Response status code: {response.status_code}")
没改动

2024-08-28 02:39 UTC, silon-j commented on libs/boost/parser.py
这里拉一下master吧

2024-08-28 02:40 UTC, silon-j requested changes
看下comment吧，另外有新的包引入，应该吧requiredment更新也带上

2024-08-28 06:10 UTC, Guanda0120 commented on apps/account/Views/login_view.py
> +            ip=request.META.get('REMOTE_ADDR', ''),
目前似乎没有这个函数~

2024-08-28 07:02 UTC, silon-j commented on apps/account/Views/login_view.py
> +            ip=request.META.get('REMOTE_ADDR', ''),
![image](https://github.com/user-attachments/assets/cbb2aa82-3673-4733-89bb-1ed07da8f62e)

2024-08-28 07:15 UTC, silon-j commented on apps/account/Views/change_password_view.py
> +        account = Account.objects.filter(username=form.username).first()
邮箱和username关系需要校验

2024-08-28 07:19 UTC, silon-j commented on apps/account/Views/login_view.py
> +        account.token_expired = timezone.now() + timedelta(seconds=settings.AUTHENTICATION_EXPIRE_TIME)
token建议用uuid4

2024-08-30 07:20 UTC, silon-j commented on apps/account/views/acount_view.py
> +        if account is None:
推荐后续Query 结果的存在检查使用 .exists()

2024-08-30 07:35 UTC, silon-j commented on libs/boost/parser.py
parser 的改动取消掉吧

2024-08-30 07:36 UTC, silon-j commented on requirements.txt
编码有问题？

2024-09-01 14:56 UTC, silon-j commented on server/settings/base.py
> +ALLOWED_HOSTS = ['*']
base 的基础配置不应该包含 * ，如果需要调试，可以再 local 里面 debug 设为 true， 或在 local 中设为 * ，使用 local 配置启动

2024-09-01 14:56 UTC, silon-j reviewed
小问题，改一下就可以合了

2024-09-01 14:58 UTC, Guanda0120 commented on server/settings/base.py
> +ALLOWED_HOSTS = ['*']
OK

2024-09-01 15:03 UTC, Guanda0120 commented on server/settings/base.py
> +ALLOWED_HOSTS = ['*']
修改完成并commit

2024-09-02 01:49 UTC, silon-j approved these changes

2024-09-02 02:17 UTC, merged